### ISSUE TITLE
Limit workers

### ISSUE THREAD

**Issue by tschmidtb51** [markuta/go-security-txt#3]
Currently, the workers can consume a lot bandwidth. It would be great, if we could limit the amount of workers - especially, if someone wants to run the tool regularly to do a long term statistic.

**Comment by markuta** [comment]
Agreed, I'll bump down the default workers from `500` to `100`, or even `50`. I think it's also worth adding an option to specify the number of workers as an argument too.

**Comment by markuta** [comment]
Fixed with https://github.com/markuta/go-security-txt/commit/599dbea2cc6f234ae74aa34918bc94f88762b5d8. 

The default workers is now at `50`. I've also added the option for users to select the number of workers to use with `-w` argument.

**Comment by tschmidtb51** [comment]
Thank you!
