### ISSUE TITLE
Potential misleading `is_file_valid`

### ISSUE THREAD

**Issue by tschmidtb51** [markuta/go-security-txt#4]
The statement `is_file_valid` is misleading as it also reports the security.txt as valid that are missing the `expires` field.

**Comment by markuta** [comment]
Fixed in https://github.com/markuta/go-security-txt/commit/a5909c73d3df32ead34f9f5a40135e91eca7674e. It's now named `is_field_found` in the CSV output.

**Comment by tschmidtb51** [comment]
Thank you
